/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import logiikka.Yatzypeli;
import yatzy.Noppakasi;
import yatzy.Pelaaja;

public class PeliIkkuna extends javax.swing.JFrame {

    private int heitot = 1;
    private Yatzypeli peli;
    private Pelaaja pelaaja;
    private boolean onkoPisteetAsetettu = false;
    private int PelaajanNro = 0;

    /**
     * Creates new form PeliIkkuna
     */
    public PeliIkkuna(Yatzypeli peli) {
        initComponents();
        setVisible(true);

        this.peli = peli;

        aloitaPeli();

        pelaa(this.peli.getPelaajaLista().get(this.PelaajanNro));
    }

    public void pelaa(Pelaaja pelaaja) {
        this.pelaaja = pelaaja;
        this.pelaajanNimi.setText("Pelaajan " + this.pelaaja.getNimi() + " vuoro.");
        this.onkoPisteetAsetettu = false;

        this.peli.getNoppakasi().heitaValitsemattomat();
        paivitaNopat();

        this.heitot = 1;
        this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());


    }

    private void aloitaPeli() {

        this.peli.luoPisteTaulukotPelaajille();


    }

    public void paivitaNopat() {
        Noppakasi kasi = this.peli.getNoppakasi();
        int eka = kasi.annaNopanNSilmaluku(1);
        int toka = kasi.annaNopanNSilmaluku(2);
        int kolmas = kasi.annaNopanNSilmaluku(3);
        int neljas = kasi.annaNopanNSilmaluku(4);
        int viides = kasi.annaNopanNSilmaluku(5);

        String ekaKuva = "/GUI/kuvat/noppa" + String.valueOf(eka) + ".jpg";
        String tokaKuva = "/GUI/kuvat/noppa" + String.valueOf(toka) + ".jpg";
        String kolmasKuva = "/GUI/kuvat/noppa" + String.valueOf(kolmas) + ".jpg";
        String neljasKuva = "/GUI/kuvat/noppa" + String.valueOf(neljas) + ".jpg";
        String viidesKuva = "/GUI/kuvat/noppa" + String.valueOf(viides) + ".jpg";

        noppa1.setIcon(new javax.swing.ImageIcon(getClass().getResource(ekaKuva)));
        noppa2.setIcon(new javax.swing.ImageIcon(getClass().getResource(tokaKuva)));
        noppa3.setIcon(new javax.swing.ImageIcon(getClass().getResource(kolmasKuva)));
        noppa4.setIcon(new javax.swing.ImageIcon(getClass().getResource(neljasKuva)));
        noppa5.setIcon(new javax.swing.ImageIcon(getClass().getResource(viidesKuva)));

    }

    private int seuuravanNumero() {
        int seuraava = this.PelaajanNro + 1;
        if (this.peli.getPelaajaLista().size() <= seuraava) {
            return 0;
        }
        return seuraava;
    }

    private void poistaNoppaValinnat() {
        this.peli.getNoppakasi().poistaKaikkiNoppaValinnat();

        nopanValinta1.setSelected(false);
        nopanValinta2.setSelected(false);
        nopanValinta3.setSelected(false);
        nopanValinta4.setSelected(false);
        nopanValinta5.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pisteNapit = new javax.swing.ButtonGroup();
        nopanValinta1 = new javax.swing.JCheckBox();
        nopanValinta2 = new javax.swing.JCheckBox();
        nopanValinta3 = new javax.swing.JCheckBox();
        nopanValinta4 = new javax.swing.JCheckBox();
        nopanValinta5 = new javax.swing.JCheckBox();
        heitaNopat = new javax.swing.JButton();
        pelaajanNimi = new javax.swing.JTextField();
        noppa1 = new javax.swing.JLabel();
        noppa2 = new javax.swing.JLabel();
        noppa3 = new javax.swing.JLabel();
        noppa4 = new javax.swing.JLabel();
        noppa5 = new javax.swing.JLabel();
        ykkoset = new javax.swing.JButton();
        kakkoset = new javax.swing.JButton();
        kolmoset = new javax.swing.JButton();
        neloset = new javax.swing.JButton();
        vitoset = new javax.swing.JButton();
        kutoset = new javax.swing.JButton();
        pari = new javax.swing.JButton();
        kaksiParia = new javax.swing.JButton();
        kolmeSamaa = new javax.swing.JButton();
        neljaSamaa = new javax.swing.JButton();
        pieniSuora = new javax.swing.JButton();
        isoSuora = new javax.swing.JButton();
        tayskasi = new javax.swing.JButton();
        sattuma = new javax.swing.JButton();
        yatzy = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        pistetaulukko = new javax.swing.JTextArea();
        seuraavaPelaaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yatzy");

        nopanValinta1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nopanValinta1ItemStateChanged(evt);
            }
        });

        nopanValinta2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nopanValinta2ItemStateChanged(evt);
            }
        });
        nopanValinta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopanValinta2ActionPerformed(evt);
            }
        });

        nopanValinta3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nopanValinta3ItemStateChanged(evt);
            }
        });
        nopanValinta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopanValinta3ActionPerformed(evt);
            }
        });

        nopanValinta4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nopanValinta4ItemStateChanged(evt);
            }
        });
        nopanValinta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopanValinta4ActionPerformed(evt);
            }
        });

        nopanValinta5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nopanValinta5ItemStateChanged(evt);
            }
        });

        heitaNopat.setText("Heitä nopat!");
        heitaNopat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heitaNopatActionPerformed(evt);
            }
        });

        pelaajanNimi.setEditable(false);

        noppa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kuvat/noppa3.jpg"))); // NOI18N

        noppa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kuvat/noppa2.jpg"))); // NOI18N

        noppa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kuvat/noppa3.jpg"))); // NOI18N

        noppa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kuvat/noppa5.jpg"))); // NOI18N

        noppa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/kuvat/noppa6.jpg"))); // NOI18N

        ykkoset.setText("Ykköset");
        pisteNapit.add(ykkoset);
        ykkoset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ykkosetActionPerformed(evt);
            }
        });

        kakkoset.setText("Kakkoset");
        pisteNapit.add(kakkoset);
        kakkoset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kakkosetActionPerformed(evt);
            }
        });

        kolmoset.setText("Kolmoset");
        pisteNapit.add(kolmoset);
        kolmoset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolmosetActionPerformed(evt);
            }
        });

        neloset.setText("Neloset");
        pisteNapit.add(neloset);
        neloset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nelosetActionPerformed(evt);
            }
        });

        vitoset.setText("Vitoset");
        pisteNapit.add(vitoset);
        vitoset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitosetActionPerformed(evt);
            }
        });

        kutoset.setText("Kutoset");
        pisteNapit.add(kutoset);
        kutoset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutosetActionPerformed(evt);
            }
        });

        pari.setText("Pari");
        pisteNapit.add(pari);
        pari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pariActionPerformed(evt);
            }
        });

        kaksiParia.setText("Kaksi paria");
        pisteNapit.add(kaksiParia);
        kaksiParia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaksiPariaActionPerformed(evt);
            }
        });

        kolmeSamaa.setText("Kolme samaa");
        pisteNapit.add(kolmeSamaa);
        kolmeSamaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolmeSamaaActionPerformed(evt);
            }
        });

        neljaSamaa.setText("Neljä samaa");
        pisteNapit.add(neljaSamaa);
        neljaSamaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neljaSamaaActionPerformed(evt);
            }
        });

        pieniSuora.setText("Pieni suora");
        pisteNapit.add(pieniSuora);
        pieniSuora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieniSuoraActionPerformed(evt);
            }
        });

        isoSuora.setText("Iso suora");
        pisteNapit.add(isoSuora);
        isoSuora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isoSuoraActionPerformed(evt);
            }
        });

        tayskasi.setText("Täyskäsi");
        pisteNapit.add(tayskasi);
        tayskasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tayskasiActionPerformed(evt);
            }
        });

        sattuma.setText("Sattuma");
        pisteNapit.add(sattuma);
        sattuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sattumaActionPerformed(evt);
            }
        });

        yatzy.setText("Yatzy");
        pisteNapit.add(yatzy);
        yatzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yatzyActionPerformed(evt);
            }
        });

        pistetaulukko.setEditable(false);
        pistetaulukko.setColumns(21);
        pistetaulukko.setLineWrap(true);
        pistetaulukko.setRows(30);
        pistetaulukko.setTabSize(2);
        pistetaulukko.setWrapStyleWord(true);
        pistetaulukko.setMaximumSize(new java.awt.Dimension(300, 500));
        pistetaulukko.setMinimumSize(new java.awt.Dimension(300, 500));
        jScrollPane2.setViewportView(pistetaulukko);

        seuraavaPelaaja.setText("Seuraava pelaaja");
        seuraavaPelaaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seuraavaPelaajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pelaajanNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kolmeSamaa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kaksiParia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kutoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vitoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(neloset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kolmoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kakkoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ykkoset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pieniSuora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(isoSuora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tayskasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sattuma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yatzy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(neljaSamaa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seuraavaPelaaja)
                                .addComponent(heitaNopat))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(noppa4)
                                        .addComponent(noppa5))
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nopanValinta5)
                                        .addComponent(nopanValinta4)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(noppa2)
                                        .addComponent(noppa3)
                                        .addComponent(noppa1))
                                    .addGap(48, 48, 48)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nopanValinta3)
                                        .addComponent(nopanValinta2)
                                        .addComponent(nopanValinta1)))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(pelaajanNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ykkoset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kakkoset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kolmoset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neloset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vitoset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kutoset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kaksiParia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kolmeSamaa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(neljaSamaa))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nopanValinta1)
                                    .addComponent(noppa1))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(noppa2)
                                    .addComponent(nopanValinta2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(noppa3)
                                    .addComponent(nopanValinta3))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nopanValinta4)
                                    .addComponent(noppa4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nopanValinta5)
                                    .addComponent(noppa5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pieniSuora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isoSuora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tayskasi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sattuma)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(heitaNopat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yatzy)
                        .addGap(8, 8, 8)
                        .addComponent(seuraavaPelaaja))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nopanValinta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopanValinta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopanValinta2ActionPerformed

    private void nopanValinta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopanValinta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopanValinta3ActionPerformed

    private void nopanValinta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopanValinta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopanValinta4ActionPerformed

    private void nopanValinta1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nopanValinta1ItemStateChanged
        Noppakasi kasi = this.peli.getNoppakasi();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            kasi.valitseNoppa(1);
        } else {
            kasi.poistaValintaNopalta(1);
        }
    }//GEN-LAST:event_nopanValinta1ItemStateChanged

    private void nopanValinta2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nopanValinta2ItemStateChanged
        Noppakasi kasi = this.peli.getNoppakasi();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            kasi.valitseNoppa(2);
        } else {
            kasi.poistaValintaNopalta(2);
        }
    }//GEN-LAST:event_nopanValinta2ItemStateChanged

    private void nopanValinta3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nopanValinta3ItemStateChanged
        Noppakasi kasi = this.peli.getNoppakasi();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            kasi.valitseNoppa(3);
        } else {
            kasi.poistaValintaNopalta(3);
        }
    }//GEN-LAST:event_nopanValinta3ItemStateChanged

    private void nopanValinta4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nopanValinta4ItemStateChanged
        Noppakasi kasi = this.peli.getNoppakasi();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            kasi.valitseNoppa(4);
        } else {
            kasi.poistaValintaNopalta(4);
        }
    }//GEN-LAST:event_nopanValinta4ItemStateChanged

    private void nopanValinta5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nopanValinta5ItemStateChanged
        Noppakasi kasi = this.peli.getNoppakasi();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            kasi.valitseNoppa(5);
        } else {
            kasi.poistaValintaNopalta(5);
        }
    }//GEN-LAST:event_nopanValinta5ItemStateChanged

    private void heitaNopatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heitaNopatActionPerformed
        if (this.heitot < 3 && this.onkoPisteetAsetettu == false) {
            this.peli.getNoppakasi().heitaValitsemattomat();
            heitot++;
            paivitaNopat();


        }
    }//GEN-LAST:event_heitaNopatActionPerformed

    private void ykkosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ykkosetActionPerformed
        if (!this.onkoPisteetAsetettu) {
            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Ykkoset");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }

    }//GEN-LAST:event_ykkosetActionPerformed

    private void seuraavaPelaajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seuraavaPelaajaActionPerformed
        if (!this.peli.jatkuukoPeli()) {
            pelinLopetus();
        } else if (!this.onkoPisteetAsetettu) {
        } else {
            int seuraava = seuuravanNumero();
            this.PelaajanNro = seuraava;
            this.pelaaja = this.peli.getPelaajaLista().get(seuraava);


            this.poistaNoppaValinnat();

            pelaa(this.pelaaja);
        }

    }//GEN-LAST:event_seuraavaPelaajaActionPerformed

    private void kakkosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kakkosetActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Kakkoset");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_kakkosetActionPerformed

    private void kolmosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolmosetActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Kolmoset");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_kolmosetActionPerformed

    private void nelosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nelosetActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Neloset");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_nelosetActionPerformed

    private void vitosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitosetActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Vitoset");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_vitosetActionPerformed

    private void kutosetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutosetActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Kutoset");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_kutosetActionPerformed

    private void pariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pariActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Pari");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_pariActionPerformed

    private void kaksiPariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaksiPariaActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Kaksi paria");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_kaksiPariaActionPerformed

    private void kolmeSamaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolmeSamaaActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Kolme samaa");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_kolmeSamaaActionPerformed

    private void neljaSamaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neljaSamaaActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Nelja samaa");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_neljaSamaaActionPerformed

    private void pieniSuoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieniSuoraActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Pieni suora");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_pieniSuoraActionPerformed

    private void isoSuoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isoSuoraActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Iso suora");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_isoSuoraActionPerformed

    private void tayskasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tayskasiActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Tayskasi");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_tayskasiActionPerformed

    private void sattumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sattumaActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Sattuma");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_sattumaActionPerformed

    private void yatzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yatzyActionPerformed
        if (!this.onkoPisteetAsetettu) {

            boolean lisattiinko = pelaaja.getTaulukko().lisaaPisteet("Yatzy");
            this.onkoPisteetAsetettu = lisattiinko;
            this.pistetaulukko.setText(this.pelaaja.getTaulukko().toStringGraafiselle());
        }
    }//GEN-LAST:event_yatzyActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton heitaNopat;
    private javax.swing.JButton isoSuora;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kakkoset;
    private javax.swing.JButton kaksiParia;
    private javax.swing.JButton kolmeSamaa;
    private javax.swing.JButton kolmoset;
    private javax.swing.JButton kutoset;
    private javax.swing.JButton neljaSamaa;
    private javax.swing.JButton neloset;
    private javax.swing.JCheckBox nopanValinta1;
    private javax.swing.JCheckBox nopanValinta2;
    private javax.swing.JCheckBox nopanValinta3;
    private javax.swing.JCheckBox nopanValinta4;
    private javax.swing.JCheckBox nopanValinta5;
    private javax.swing.JLabel noppa1;
    private javax.swing.JLabel noppa2;
    private javax.swing.JLabel noppa3;
    private javax.swing.JLabel noppa4;
    private javax.swing.JLabel noppa5;
    private javax.swing.JButton pari;
    private javax.swing.JTextField pelaajanNimi;
    private javax.swing.JButton pieniSuora;
    private javax.swing.ButtonGroup pisteNapit;
    private javax.swing.JTextArea pistetaulukko;
    private javax.swing.JButton sattuma;
    private javax.swing.JButton seuraavaPelaaja;
    private javax.swing.JButton tayskasi;
    private javax.swing.JButton vitoset;
    private javax.swing.JButton yatzy;
    private javax.swing.JButton ykkoset;
    // End of variables declaration//GEN-END:variables

    private void pelinLopetus() {
        throw new UnsupportedOperationException("Not yet implemented");
    }
}
